# Generated by Django 5.1.1 on 2026-01-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dataCriacao',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
